services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - shared_network
    ports:
      - "${APP_PORT:-3030}:${APP_PORT:-3030}"
    expose:
      - "${APP_PORT:-3030}"
    environment:
      - APP_PORT=${APP_PORT:-3030}
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql
    restart: always
    env_file:
      - .env
    networks:
      - shared_network
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

volumes:
  my-db:
networks:
  shared_network:
    external: true
